<?xml version="1.0" encoding="utf-8"?><Database Name="LaFemmeDatabase" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\LaFemmeDatabase.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LaFemmeDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="User">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="login" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Articles" Member="Articles">
    <Type Name="Articles">
      <Column Name="a_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="a_author" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="a_name" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="a_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>